/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        // Guofeng color palette
        "gufeng-primary": "#4a6545",
        "gufeng-secondary": "#7b5455",
        "gufeng-tertiary": "#705b36",
        "gufeng-accent-light": "#a8c69f",
        "gufeng-accent-pink": "#d4a5a5",
        "gufeng-accent-gold": "#e2c799",
        "gufeng-background": "#fbf9f5",
        "gufeng-surface": "#f5f3ef",
        "gufeng-outline": "#c3c8bd",
        "gufeng-text": "#1b1c1a",
        "gufeng-text-muted": "#434840",
        // Existing colors preserved
        "on-secondary-fixed": "#2f1314",
        "background": "#fbf9f5",
        "on-tertiary-fixed": "#271900",
        "tertiary-fixed-dim": "#dec395",
        "tertiary": "#705b36",
        "secondary-fixed-dim": "#ecbbba",
        "on-primary": "#ffffff",
        "surface-bright": "#fbf9f5",
        "on-primary-fixed": "#082007",
        "on-secondary-fixed-variant": "#603d3e",
        "on-tertiary-fixed-variant": "#564421",
        "outline": "#73796f",
        "surface-variant": "#e4e2de",
        "surface-container-low": "#f5f3ef",
        "surface-container": "#efeeea",
        "outline-variant": "#c3c8bd",
        "on-surface-variant": "#434840",
        "tertiary-fixed": "#fbdfaf",
        "error-container": "#ffdad6",
        "secondary-container": "#fdcbcb",
        "on-surface": "#1b1c1a",
        "surface-container-lowest": "#ffffff",
        "on-background": "#1b1c1a",
        "on-tertiary": "#ffffff",
        "inverse-surface": "#30312e",
        "on-primary-container": "#395334",
        "inverse-on-surface": "#f2f0ed",
        "secondary": "#7b5455",
        "surface-dim": "#dbdad6",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "on-secondary": "#ffffff",
        "surface-container-high": "#eae8e4",
        "tertiary-container": "#d4ba8d",
        "primary-fixed-dim": "#b1cfa7",
        "on-secondary-container": "#795354",
        "surface": "#fbf9f5",
        "primary": "#4a6545",
        "on-tertiary-container": "#5d4a26",
        "primary-container": "#a8c69f",
        "surface-container-highest": "#e4e2de",
        "on-error-container": "#93000a",
        "inverse-primary": "#b1cfa7",
        "secondary-fixed": "#ffdad9",
        "primary-fixed": "#ccebc2",
        "surface-tint": "#4a6545",
        "on-primary-fixed-variant": "#334d2f"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "gutter": "12px",
        "margin-tablet": "40px",
        "xl": "32px",
        "sm": "8px",
        "unit": "4px",
        "md": "16px",
        "lg": "24px",
        "margin-mobile": "16px",
        "xs": "4px"
      },
      fontFamily: {
        "headline": ["Noto Serif", "Noto Serif SC", "Noto Serif TC", "serif"],
        "body": ["system-ui", "-apple-system", "BlinkMacSystemFont", "sans-serif"],
        "label": ["system-ui", "-apple-system", "BlinkMacSystemFont", "sans-serif"],
        "body-lg": ["Be Vietnam Pro", "sans-serif"],
        "body-md": ["Be Vietnam Pro", "sans-serif"],
        "headline-lg-mobile": ["Noto Serif", "serif"],
        "label-sm": ["Work Sans", "sans-serif"],
        "headline-lg": ["Noto Serif", "serif"],
        "headline-md": ["Noto Serif", "serif"],
        "label-lg": ["Work Sans", "sans-serif"]
      },
      fontSize: {
        "body-lg": ["18px", { lineHeight: "26px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "headline-lg": ["28px", { lineHeight: "36px", fontWeight: "700" }],
        "headline-md": ["22px", { lineHeight: "28px", fontWeight: "600" }],
        "label-lg": ["14px", { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "600" }]
      }
    }
  },
  plugins: [],
}